/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32l4xx.h"
#include "uart.h"
#include "exception_handlers.h"

int main(void) {
    init_stacks(); // Stack-Initialisierung
    uart2_init(115200);
    uart_printf("Exception Handler Test ready.\n");
    uart_printf("Commands: 1=UsageFault(div0), 2=UsageFault(undIns), 3=BusFault, 4=SVC\n");

    for (;;) {
        int c = uart2_getc_blocking();
        uart_printf("Command: '%c'\n", c);
        test_exceptions((char)c);
    }
}
